from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Sequence

from .qa_input_manifest import load_input_manifest_index, required_prompt_intent_fields


_DEFAULT_SPLITS = (
    ("front", Path("input_split") / "front"),
    ("three_quarter", Path("input_split") / "three_quarter"),
)


def _first_text(value: Any) -> str:
    return str(value or "").strip()


def _seed_or_unavailable_ready(item: Dict[str, Any]) -> bool:
    return item.get("seed") is not None or bool(_first_text(item.get("seed_unavailable_reason")))


def _coverage(entries: Sequence[Dict[str, Any]]) -> Dict[str, float]:
    total = max(1, len(entries))
    return {
        "prompt_id": sum(1 for item in entries if _first_text(item.get("prompt_id"))) / total,
        "seed": sum(1 for item in entries if _seed_or_unavailable_ready(item)) / total,
        "seed_available": sum(1 for item in entries if item.get("seed") is not None) / total,
        "seed_unavailable_reason": sum(1 for item in entries if _first_text(item.get("seed_unavailable_reason"))) / total,
        "anchor_source": sum(1 for item in entries if _first_text(item.get("anchor_source"))) / total,
        "intended_view": sum(1 for item in entries if _first_text(item.get("intended_view") or item.get("view_expected"))) / total,
    }


def _missing_count(entries: Sequence[Dict[str, Any]], field_name: str) -> int:
    if field_name == "seed":
        return sum(1 for item in entries if not _seed_or_unavailable_ready(item))
    if field_name == "intended_view":
        return sum(1 for item in entries if not _first_text(item.get("intended_view") or item.get("view_expected")))
    return sum(1 for item in entries if not _first_text(item.get(field_name)))


def _round_coverage(payload: Dict[str, float]) -> Dict[str, float]:
    return {key: round(float(value), 4) for key, value in payload.items()}


def _split_plan(base_dir: Path, label: str, relative_dir: Path) -> Dict[str, Any]:
    input_dir = (base_dir / relative_dir).resolve()
    manifest = load_input_manifest_index(input_dir)
    entries = manifest.get("entries") if isinstance(manifest.get("entries"), list) else []
    coverage = _coverage(entries)
    required_fields = required_prompt_intent_fields()
    missing_counts = {field: _missing_count(entries, field) for field in required_fields}
    missing_fields = [field for field, count in missing_counts.items() if count > 0]
    item_count = len(entries)
    ready = bool(item_count) and not missing_fields
    return {
        "split": label,
        "input_dir": str(input_dir),
        "manifest_path": manifest.get("path"),
        "available": bool(manifest.get("available")),
        "item_count": item_count,
        "required_fields": required_fields,
        "field_policy": {
            "seed": "ready when seed is present, or seed_unavailable_reason documents why the generator did not expose it",
            "prompt_id": "must identify the real prompt slot, prompt file, or batch prompt family; do not fabricate",
            "anchor_source": "may be shared only when every image in this split used the same confirmed truth-anchor inputs",
        },
        "field_coverage": _round_coverage(coverage),
        "missing_counts": missing_counts,
        "missing_fields": missing_fields,
        "ready_for_clean_replay": ready,
        "safe_default_candidates": {
            "seed_unavailable_reason": {
                "value": "nano_banana_seed_not_exposed",
                "safe_to_apply_when": "Nano Banana did not expose per-image seeds for this batch.",
            },
            "generator_name": {
                "value": "nano_banana",
                "safe_to_apply_when": "This split was generated by Nano Banana.",
            },
            "anchor_source": {
                "value": "A-Core_01_0deg_MASTER + Task-63987060-116-1",
                "safe_to_apply_when": "Every image used the face master and body master as generation references.",
            },
        },
        "manual_required_fields": [
            {
                "field": "prompt_id",
                "why": "Only the operator can confirm which prompt file, prompt slot, or batch prompt family produced this split.",
            }
        ] if "prompt_id" in missing_fields else [],
        "example_fill_command": (
            ".\\.venv\\Scripts\\python.exe .\\check_consistency.py --workflow fill_input_manifest_defaults "
            f"--input-dir {relative_dir} "
            "--manifest-seed-unavailable-reason nano_banana_seed_not_exposed "
            "--manifest-generator-name nano_banana "
            "--manifest-anchor-source \"<confirmed_anchor_source>\" "
            "--manifest-prompt-id \"<actual_prompt_id_or_batch_id>\""
        ),
    }


def build_manifest_completion_plan(
    *,
    base_dir: Path,
    output_file: Path,
) -> Dict[str, Any]:
    splits = [_split_plan(base_dir, label, relative_dir) for label, relative_dir in _DEFAULT_SPLITS]
    ready = all(bool(row.get("ready_for_clean_replay")) for row in splits)
    blocked = [row.get("split") for row in splits if not bool(row.get("ready_for_clean_replay"))]
    payload = {
        "schema_version": "input_manifest_completion_plan_v1",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "purpose": "Make clean-lane replay metadata completion explicit before invariance gates are judged.",
        "overall_status": "READY_FOR_CLEAN_REPLAY" if ready else "NEEDS_MANIFEST_COMPLETION",
        "ready_for_clean_replay": ready,
        "blocked_splits": blocked,
        "splits": splits,
        "operator_policy": {
            "do_not_fabricate_prompt_id": True,
            "do_not_fabricate_seed": True,
            "seed_unavailable_reason_is_allowed": True,
            "shared_anchor_source_requires_confirmation": True,
        },
        "next_actions": [
            "Fill seed_unavailable_reason if Nano Banana did not expose seeds.",
            "Confirm anchor_source only if the whole split used the same truth-anchor inputs.",
            "Fill prompt_id from the real prompt file, slot, or batch prompt family.",
            "Rerun clean front and three_quarter replay after manifests are complete.",
        ],
    }
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return payload
